### ISSUE TITLE
feat: Persistent volumes across deployments

### ISSUE THREAD

**Issue by antocommi** [allegroai/clearml-helm-charts#151]
Going through the repo i saw that: 
- mongodb, fileserver are **Deployments**
- redis, elasticsearch are StatefulSets

Hence, each time I uninstall the clearml-server it keeps deleting our experiments data. Is there a way to solve the problem? Can be solved converting the deployments to statefulsets as well? 

Is it possible to use an ad-hoc volumes of mongodb to solve the problem?

**Comment by valeriano-manassero** [comment]
Hi,
maybe I misunderstood the request but deleting an installed chart means you don't need anymore the entire stack.
More than reusing existing PVC it's better to simply upgrade chart installation than removing it and reinstalling.

Basically Helm deletes just what it creates so this is why deployment PVC are deleted while statefulset ones are not (because they are created by statefulset itself and not Helm). External chart can be reconfigured following their configs while we Fileserver is indeed deploying a Deployment.

If you want to avoid PVC created by Helm to be deleted, you should mark them with annotation `helm.sh/resource-policy: "keep"`.

**Comment by antocommi** [comment]
**I would like to maintain experiment data across deployments** (helm install/uninstall) as in redis and elasticsearch volumes that is maintained after an helm uninstall (maybe due to the fact that it's a statefulset as you said)
