### ISSUE TITLE
Improve repository reference

### ISSUE THREAD

**Issue by valeriano-manassero** [allegroai/clearml-helm-charts#169]
This is a general note to improve management of referred image repository in every chart.

Actually the form is:

```
image:
    repository: "allegroai/clearml"
```

A better solution would be:

```
image:
    repository: "allegroai"
    name: "clearml"
```

Unfortunately, implementing this could break existing installation already overriding `image.repository` with a repo/image string.
Need to find a solution.

**Comment by awaizman1** [comment]
Thanks @valeriano-manassero,

a recommended approach is similar to bitnami. Check out https://github.com/bitnami/charts/tree/main/bitnami/postgresql/#installing-the-chart for example. 
it has a global.imageRegistry and for each image in the chart image.registry, image.repository and image.tag. 

This is very convenient since u can override the registry to all images at once or per image for finer granularity.
